import uuid

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from institute.modules.auth.models import User


class UserRepository:
    """
    Responsible for all user-related interactions with the database.

    The service doesn't know how the user is stored — it only requests by email
    or by id. This allows changing the database without changing the business logic.
    """

    def __init__(self, db: AsyncSession) -> None:
        self._db = db

    async def create(self, email: str, hashed_password: str) -> User:
        user = User(email=email, hashed_password=hashed_password)
        self._db.add(user)
        await self._db.flush()  # Send to the bank but don't commit.
        await self._db.refresh(
            user
        )  # reloads with data generated by the database (id, created_at)
        return user

    async def get_by_email(self, email: str) -> User | None:
        result = await self._db.execute(select(User).where(User.email == email))
        return result.scalar_one_or_none()

    async def get_by_id(self, user_id: uuid.UUID) -> User | None:
        result = await self._db.execute(select(User).where(User.id == user_id))
        return result.scalar_one_or_none()
